"""Cloudflare Worker bundle generator.

The Worker is the **control plane**: it serves the exact same dashboard
HTML as the offline server, stores settings/pairs in KV, keeps API keys as
Worker secrets, proxies the OpenAI/OpenRouter connection test, and holds a
run registry that the Python **compute plane** publishes results into. A
Worker cannot run the numpy search (CPU-time limits) and must not compute
fitness or store lockbox data — the same governance as everywhere else.

`build_worker_bundle` emits a directory ready for `wrangler deploy`.
Deploying requires a real Cloudflare account, so actual deployment is
PENDING with the exact commands in the generated README.
"""
from __future__ import annotations

import json
from pathlib import Path

_DASHBOARD = Path(__file__).with_name("dashboard.html")

_WRANGLER_TOML = """\
name = "evoquant-dashboard"
main = "worker.js"
compatibility_date = "2024-11-01"

# Settings, pair registry, and published run results live in KV.
# Create the namespaces then paste their ids below:
#   wrangler kv namespace create EVOQUANT_KV
#   wrangler kv namespace create EVOQUANT_RUNS
kv_namespaces = [
  { binding = "EVOQUANT_KV",   id = "REPLACE_WITH_KV_ID" },
  { binding = "EVOQUANT_RUNS", id = "REPLACE_WITH_RUNS_ID" },
]

# API keys are SECRETS, never committed:
#   wrangler secret put OPENAI_API_KEY
#   wrangler secret put OPENROUTER_API_KEY
#   wrangler secret put EVOQUANT_RUNNER_TOKEN   # the Python runner's auth
"""

# The Worker JS. The dashboard HTML is injected as a JSON string constant so
# the exact same UI runs on Cloudflare and offline.
_WORKER_JS_TEMPLATE = """\
// GENERATED by evoquant — Cloudflare Worker control plane.
// Compute (the numpy search) stays in Python. This Worker is control-only:
// it never computes fitness and never stores lockbox data.
const DASHBOARD_HTML = %(dashboard_json)s;

const PROVIDERS = {
  openai: "https://api.openai.com/v1/chat/completions",
  openrouter: "https://openrouter.ai/api/v1/chat/completions",
};

function json(obj, status = 200) {
  return new Response(JSON.stringify(obj), {
    status,
    headers: { "content-type": "application/json" },
  });
}

async function llmTest(env, body) {
  const provider = (body.provider || "").toLowerCase();
  const endpoint = PROVIDERS[provider];
  if (!endpoint) return json({ ok: false, message: "unknown provider" }, 400);
  const key = body.api_key ||
    (provider === "openai" ? env.OPENAI_API_KEY : env.OPENROUTER_API_KEY);
  if (!key) return json({ ok: false, message: "no API key (set the secret)" }, 400);
  const headers = { "content-type": "application/json", authorization: `Bearer ${key}` };
  if (provider === "openrouter") headers["HTTP-Referer"] = "https://evoquant";
  const t0 = Date.now();
  const r = await fetch(endpoint, {
    method: "POST",
    headers,
    body: JSON.stringify({
      model: body.model,
      messages: [{ role: "user", content: "Reply with exactly: ok" }],
      temperature: 0.2,
    }),
  });
  if (!r.ok) return json({ ok: false, message: `HTTP ${r.status}`, body: (await r.text()).slice(0, 300) }, 502);
  const doc = await r.json();
  const content = doc?.choices?.[0]?.message?.content ?? "";
  return json({
    ok: true, provider, model: body.model,
    latency_s: (Date.now() - t0) / 1000,
    reply_preview: String(content).slice(0, 40),
  });
}

function requireRunner(request, env) {
  const tok = request.headers.get("x-evoquant-runner-token") || "";
  return env.EVOQUANT_RUNNER_TOKEN && tok === env.EVOQUANT_RUNNER_TOKEN;
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const p = url.pathname;
    try {
      if (request.method === "GET" && (p === "/" || p === "/index.html"))
        return new Response(DASHBOARD_HTML, { headers: { "content-type": "text/html; charset=utf-8" } });

      if (request.method === "GET" && p === "/api/config") {
        const cfg = JSON.parse((await env.EVOQUANT_KV.get("config")) || "{}");
        cfg.secrets_present = {
          openai_api_key: !!env.OPENAI_API_KEY,
          openrouter_api_key: !!env.OPENROUTER_API_KEY,
        };
        cfg.mode = "cloudflare";
        return json(cfg);
      }
      if (request.method === "PUT" && p === "/api/config") {
        const body = await request.json();
        delete body.secrets; // secrets are wrangler secrets, never KV
        await env.EVOQUANT_KV.put("config", JSON.stringify(body));
        return json({ ok: true });
      }
      if (request.method === "POST" && p === "/api/llm-test")
        return await llmTest(env, await request.json());

      if (request.method === "GET" && p === "/api/pairs") {
        const pairs = JSON.parse((await env.EVOQUANT_KV.get("pairs")) || "[]");
        return json({ pairs });
      }
      if (request.method === "GET" && p === "/api/runs") {
        const list = await env.EVOQUANT_RUNS.list({ prefix: "run:" });
        const runs = [];
        for (const k of list.keys) {
          const v = await env.EVOQUANT_RUNS.get(k.name);
          if (v) runs.push(JSON.parse(v));
        }
        runs.sort((a, b) => (b.started_at || "").localeCompare(a.started_at || ""));
        return json({ runs });
      }
      if (request.method === "GET" && p.startsWith("/api/runs/")) {
        const id = p.split("/")[3];
        const rest = p.split("/")[4];
        const status = await env.EVOQUANT_RUNS.get("run:" + id);
        if (!status) return json({ error: "not found" }, 404);
        const doc = JSON.parse(status);
        if (!rest) return json(doc);
        const report = await env.EVOQUANT_RUNS.get("report:" + id);
        if (rest === "report") return json(report ? JSON.parse(report) : { error: "no report" });
        if (rest === "download")
          return new Response(report || "{}", {
            headers: {
              "content-type": "application/json",
              "content-disposition": `attachment; filename="evoquant_${id}_report.json"`,
            },
          });
      }

      // ---- runner ingestion (Python compute plane -> control plane) ----
      if (request.method === "POST" && p === "/api/runner/publish") {
        if (!requireRunner(request, env)) return json({ error: "unauthorized" }, 401);
        const body = await request.json();
        if (body.status) await env.EVOQUANT_RUNS.put("run:" + body.run_id, JSON.stringify(body.status));
        if (body.report) await env.EVOQUANT_RUNS.put("report:" + body.run_id, JSON.stringify(body.report));
        if (body.pairs) await env.EVOQUANT_KV.put("pairs", JSON.stringify(body.pairs));
        return json({ ok: true });
      }

      return json({ error: "not found", path: p }, 404);
    } catch (e) {
      return json({ error: String(e) }, 500);
    }
  },
};
"""

_README = """\
# evoquant Cloudflare Worker (control plane)

This Worker serves the dashboard and stores config / pair registry / run
results. **It does not run the search** — Cloudflare Workers have CPU-time
limits the numpy evolutionary search would exceed, and by policy the Worker
never computes fitness or stores lockbox data. The Python engine is the
compute plane; it publishes results to the Worker.

## Deploy (requires a Cloudflare account — PENDING until you run it)

```bash
npm i -g wrangler
wrangler login

wrangler kv namespace create EVOQUANT_KV
wrangler kv namespace create EVOQUANT_RUNS
# paste the two ids into wrangler.toml

wrangler secret put OPENAI_API_KEY        # optional
wrangler secret put OPENROUTER_API_KEY    # optional (free models)
wrangler secret put EVOQUANT_RUNNER_TOKEN # shared secret for the runner

wrangler deploy
```

## Publish a run from the Python compute plane

```bash
# after `evoquant run ...`, push status + report to the Worker:
curl -X POST https://<your-worker>/api/runner/publish \\
  -H "x-evoquant-runner-token: $EVOQUANT_RUNNER_TOKEN" \\
  -H "content-type: application/json" \\
  -d @publish_payload.json
```

`publish_payload.json` = `{ "run_id": "...", "status": {...}, "report": {...}, "pairs": [...] }`.

## Endpoints (identical shape to the offline server)

- `GET  /`                     dashboard
- `GET  /api/pairs`            pair registry (KV)
- `GET|PUT /api/config`        settings (KV; secrets stay wrangler secrets)
- `POST /api/llm-test`         OpenAI/OpenRouter connectivity check
- `GET  /api/runs`             list runs
- `GET  /api/runs/{id}`        run status
- `GET  /api/runs/{id}/report` full report
- `GET  /api/runs/{id}/download` report as attachment
- `POST /api/runner/publish`   runner ingestion (token-gated)
"""


def build_worker_bundle(out_dir: str | Path) -> dict[str, str]:
    """Emit a wrangler-ready Worker bundle embedding the shared dashboard."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    dashboard = _DASHBOARD.read_text()
    worker_js = _WORKER_JS_TEMPLATE % {"dashboard_json": json.dumps(dashboard)}
    (out / "worker.js").write_text(worker_js)
    (out / "wrangler.toml").write_text(_WRANGLER_TOML)
    (out / "README.md").write_text(_README)
    return {
        "worker": str(out / "worker.js"),
        "wrangler_toml": str(out / "wrangler.toml"),
        "readme": str(out / "README.md"),
    }
