from __future__ import annotations

import hashlib

import numpy as np
import pytest

from evoquant.features.ast import Node
from evoquant.genome.generator import PERIODS
from evoquant.genome.genome import random_genome
from evoquant.mql5.exporter import _WINDOW_OPS, ExportError, export_ea, strategy_tester_ini
from tests.conftest import make_spec

SPEC = make_spec()


def test_export_is_deterministic():
    g = random_genome(np.random.default_rng(1), "TESTUSDT")
    a = export_ea(g, SPEC)
    b = export_ea(g, SPEC)
    assert hashlib.sha256(a.encode()).hexdigest() == hashlib.sha256(b.encode()).hexdigest()


def test_twenty_random_genomes_export_without_error():
    rng = np.random.default_rng(2)
    for _ in range(20):
        src = export_ea(random_genome(rng, "TESTUSDT"), SPEC)
        assert "OnTick" in src and "GENERATED by evoquant" in src


def test_grammar_coverage_matches_generator():
    """Every op the genome generator can emit must have a translation."""
    translated = (
        set(_WINDOW_OPS)
        | {"close", "open", "high", "low", "volume", "constant"}
        | {"abs", "neg", "not", "add", "sub", "gt", "lt", "and", "or"}
        | {"cross_above", "cross_below", "ema", "atr", "chop"}
    )
    # ops reachable from generator.py (structural superset check)
    from evoquant.features.registry import REGISTRY

    assert set(REGISTRY) <= translated


def test_unknown_op_raises():
    import dataclasses

    g = random_genome(np.random.default_rng(3), "X")
    bad = dataclasses.replace(
        g, entry_long=Node(op="gt", children=(Node(op="close"), Node(op="close")))
    )
    # sabotage the tree after validation by injecting an unregistered op
    evil = dataclasses.replace(
        bad,
        entry_long=Node(
            op="gt",
            children=(
                Node(op="quantum_indicator", period=5, children=(Node(op="close"),)),
                Node(op="close"),
            ),
        ),
    )
    with pytest.raises(ExportError):
        export_ea(evil, SPEC)


def test_genome_metadata_embedded():
    g = random_genome(np.random.default_rng(4), "BNBUSDT")
    src = export_ea(g, SPEC)
    assert g.genome_hash() in src
    assert f"const double SL_ATR   = {g.risk.sl_atr}" in src
    assert f"const int    MAX_BARS = {g.risk.max_bars}" in src
    assert f"const double LOT_STEP = {SPEC.lot_step}" in src


def test_min_bars_covers_lookback():
    g = random_genome(np.random.default_rng(5), "X")
    src = export_ea(g, SPEC)
    min_bars = int(src.split("const int    MIN_BARS = ")[1].split(";")[0])
    assert min_bars >= max(PERIODS)  # at least the largest possible period


def test_subexpressions_are_shared():
    """Identical subtrees compile to one function (semantic-hash naming)."""
    rng = np.random.default_rng(6)
    g = random_genome(rng, "X")
    src = export_ea(g, SPEC)
    # every generated Expr_ function name must be defined exactly once
    names = {
        line.split("(")[0].split()[-1]
        for line in src.splitlines()
        if line.startswith("double Expr_")
    }
    for name in names:
        assert src.count(f"double {name}(const int s)") == 1


class TestTesterConfig:
    def test_real_tick_model_pinned(self):
        ini = strategy_tester_ini("BNBUSDT", "EA.mq5", "2024.01.01", "2025.01.01", 1_000_000)
        assert "Model=4" in ini  # Every tick based on real ticks
        assert "Symbol=BNBUSDT" in ini
        assert "FromDate=2024.01.01" in ini
        assert "Deposit=1000000" in ini
        assert "Optimization=0" in ini
